services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HauerHeinrich\HhSlider\:
    resource: '../Classes/*'

  HauerHeinrich\HhSlider\Evaluation\JsonEvaluation:
    public: true


  HauerHeinrich\HhSlider\EventListener\IsContentUsedOnPageLayoutEvent:
    tags:
      - name: event.listener
        identifier: 'hh-slider/IsContentUsedOnPageLayoutEvent'
        event: TYPO3\CMS\Backend\View\Event\IsContentUsedOnPageLayoutEvent
