services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HauerHeinrich\HhSlider\:
    resource: '../Classes/*'

  HauerHeinrich\HhSlider\Evaluation\JsonEvaluation:
    public: true

  HauerHeinrich\HhSlider\Tca\ItemProcFunc:
    public: true

  HauerHeinrich\HhSlider\EventListener\IsContentUsedOnPageLayoutEvent:
    tags:
      - name: event.listener
        identifier: 'hh-slider/IsContentUsedOnPageLayoutEvent'
        event: TYPO3\CMS\Backend\View\Event\IsContentUsedOnPageLayoutEvent

  HauerHeinrich\HhSlider\EventListener\ModifyDatabaseQueryForContentEventListener:
    tags:
      - name: event.listener
        identifier: 'hh-slider/modify-database-query-for-content'
        method: 'modify'
        event: TYPO3\CMS\Backend\View\Event\ModifyDatabaseQueryForContentEvent

  HauerHeinrich\HhSlider\EventListener\ModifyDatabaseQueryForRecordListingEventListener:
    tags:
      - name: event.listener
        identifier: 'hh-slider/modify-database-query-for-record'
        method: 'modify'
        event: TYPO3\CMS\Backend\View\Event\ModifyDatabaseQueryForRecordListingEvent
